/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AGHEyeRingLogo: typeof import('./src/components/Element/AGHEyeRingLogo.vue')['default']
    AGHLogo: typeof import('./src/components/Element/AGHLogo.vue')['default']
    CompanyLogo: typeof import('./src/components/Element/CompanyLogo.vue')['default']
    DashLine: typeof import('./src/components/Element/DashLine.vue')['default']
    EventLogo: typeof import('./src/components/Element/EventLogo.vue')['default']
    IconFa6BrandsFacebookF: typeof import('~icons/fa6-brands/facebook-f')['default']
    IconFa6BrandsLinkedinIn: typeof import('~icons/fa6-brands/linkedin-in')['default']
    IconFa6BrandsMedium: typeof import('~icons/fa6-brands/medium')['default']
    IconFa6BrandsTwitter: typeof import('~icons/fa6-brands/twitter')['default']
    IconIcOutlineFileDownload: typeof import('~icons/ic/outline-file-download')['default']
    IconIcRoundAccessTimeFilled: typeof import('~icons/ic/round-access-time-filled')['default']
    IconIcRoundClose: typeof import('~icons/ic/round-close')['default']
    IconIcRoundLocalPhone: typeof import('~icons/ic/round-local-phone')['default']
    IconIcRoundLocationOn: typeof import('~icons/ic/round-location-on')['default']
    IconIcRoundMail: typeof import('~icons/ic/round-mail')['default']
    MainBanner: typeof import('./src/components/Layout/MainBanner.vue')['default']
    MainContent: typeof import('./src/components/Layout/MainContent.vue')['default']
    MainFooter: typeof import('./src/components/Layout/MainFooter.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SpotlightTitle: typeof import('./src/components/Element/SpotlightTitle.vue')['default']
    TargetRing: typeof import('./src/components/Element/TargetRing.vue')['default']
  }
}
