/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AGHEyeRingLogo: typeof import('./src/components/Element/AGHEyeRingLogo.vue')['default']
    AGHLogo: typeof import('./src/components/Element/AGHLogo.vue')['default']
    CompanyLogo: typeof import('./src/components/Element/CompanyLogo.vue')['default']
    DashLine: typeof import('./src/components/Element/DashLine.vue')['default']
    EventLogo: typeof import('./src/components/Element/EventLogo.vue')['default']
    IconIcClock: typeof import('~icons/ic/clock')['default']
    IconIcRoundAccessTimeFilled: typeof import('~icons/ic/round-access-time-filled')['default']
    IconIcRoundClose: typeof import('~icons/ic/round-close')['default']
    IconIcRoundLocationOn: typeof import('~icons/ic/round-location-on')['default']
    IconIcTime: typeof import('~icons/ic/time')['default']
    IconMdiTime: typeof import('~icons/mdi/time')['default']
    MainBanner: typeof import('./src/components/Layout/MainBanner.vue')['default']
    MainContent: typeof import('./src/components/Layout/MainContent.vue')['default']
    OutlineTextGradient: typeof import('./src/components/Effects/OutlineTextGradient.vue')['default']
    SpotlightTitle: typeof import('./src/components/Element/SpotlightTitle.vue')['default']
    TargetRing: typeof import('./src/components/Element/TargetRing.vue')['default']
  }
}
