/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CompanyLogo: typeof import('./src/components/Element/CompanyLogo.vue')['default']
    EventLogo: typeof import('./src/components/Element/EventLogo.vue')['default']
    MainBanner: typeof import('./src/components/Layout/MainBanner.vue')['default']
  }
}
